version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend-nestjs"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
